type: sim900
num_children: 8
children:
  - kind: sim928
    ref: sim900/modules/sim928_Slot1.yml
    key: "1"
  - kind: sim970
    ref: sim900/modules/sim970_Slot2.yml
    key: "2"
  - kind: sim928
    ref: sim900/modules/sim928_Slot3.yml
    key: "3"
  - kind: sim928
    ref: sim900/modules/sim928_Slot4.yml
    key: "4"
  - kind: sim970
    ref: sim900/modules/sim970_Slot5.yml
    key: "5"
  - kind: sim970
    ref: sim900/modules/sim970_Slot6.yml
    key: "6"
  # - kind: sim928
  #   ref: sim900/modules/sim928_Slot7.yml
  #   key: "7"
  - kind: sim970
    ref: sim900/modules/sim970_Slot8.yml
    key: "8"
